### ISSUE TITLE
add multicast support for destination

### ISSUE THREAD

**Issue by ghost** [ampledata/pytak#8]
https://github.com/ampledata/pytak/blob/e8a1478c88c0b9597933e30f78a56b78bcb6dfeb/pytak/functions.py#L132

Please consider adding UDP multicast support for CoT destination URL/IP address.

**Comment by ampledata** [comment]
```
gba@MYPC:~$ DEBUG=1 stratuxcot -U udp+multicast:239.2.3.1:6969 -W ws://192.168.0.146/traffic
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "/home/gba/.local/bin/stratuxcot", line 10, in <module>
    sys.exit(cli())
  File "/home/gba/.local/lib/python3.7/site-packages/stratuxcot/commands.py", line 80, in cli
    asyncio.run(main(opts), debug=bool(os.environ.get('DEBUG')))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/gba/.local/lib/python3.7/site-packages/stratuxcot/commands.py", line 34, in main
    reader, writer = await pytak.protocol_factory(cot_url)
  File "/home/gba/.local/lib/python3.7/site-packages/pytak/functions.py", line 137, in protocol_factory
    "Please specify a protocol in your URL, for example: tcp:xxx or "
Exception: Please specify a protocol in your URL, for example: tcp:xxx or udp:xxx
```
